import type { editor } from "monaco-editor";

export const IDE_THEME: editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { token: "comment", foreground: "546478", fontStyle: "italic" },
    { token: "keyword", foreground: "569cd6" },
    { token: "keyword.control", foreground: "c586c0" },
    { token: "string", foreground: "ce9178" },
    { token: "string.escape", foreground: "d7ba7d" },
    { token: "number", foreground: "b5cea8" },
    { token: "number.hex", foreground: "b5cea8" },
    { token: "type", foreground: "4ec9b0" },
    { token: "class", foreground: "4ec9b0" },
    { token: "struct", foreground: "4ec9b0" },
    { token: "interface", foreground: "b8d7a3" },
    { token: "enum", foreground: "4ec9b0" },
    { token: "delegate", foreground: "4ec9b0" },
    { token: "namespace", foreground: "4ec9b0" },
    { token: "function", foreground: "dcdcaa" },
    { token: "method", foreground: "dcdcaa" },
    { token: "variable", foreground: "9cdcfe" },
    { token: "parameter", foreground: "9cdcfe" },
    { token: "field", foreground: "9cdcfe" },
    { token: "property", foreground: "9cdcfe" },
    { token: "operator", foreground: "d4d4d4" },
    { token: "delimiter", foreground: "d4d4d4" },
    { token: "predefined", foreground: "4fc1ff" },
    { token: "xmlDocCommentName", foreground: "546478" },
    { token: "xmlDocCommentDelimiter", foreground: "546478" },
    { token: "xmlDocCommentAttribute", foreground: "546478" },
  ],
  colors: {
    "editor.background": "#070a0e",
    "editor.foreground": "#f0f4f8",
    "editor.lineHighlightBackground": "#0e1319",
    "editor.lineHighlightBorder": "#00000000",
    "editor.selectionBackground": "#264f78",
    "editor.inactiveSelectionBackground": "#264f7855",
    "editorLineNumber.foreground": "#374151",
    "editorLineNumber.activeForeground": "#546478",
    "editorCursor.foreground": "#60a5fa",
    "editor.findMatchBackground": "#9e6a03aa",
    "editor.findMatchHighlightBackground": "#f2cc6044",
    "editorBracketMatch.background": "#3b5571aa",
    "editorBracketMatch.border": "#60a5fa",
    "editorGutter.background": "#070a0e",
    "editorWidget.background": "#0e1319",
    "editorWidget.border": "#1f2937",
    "editorSuggestWidget.background": "#0e1319",
    "editorSuggestWidget.border": "#1f2937",
    "editorSuggestWidget.selectedBackground": "#182030",
    "editorSuggestWidget.highlightForeground": "#60a5fa",
    "editorHoverWidget.background": "#0e1319",
    "editorHoverWidget.border": "#1f2937",
    "minimap.background": "#070a0e",
    "minimap.selectionHighlight": "#264f78",
    "scrollbar.shadow": "#00000000",
    "scrollbarSlider.background": "#1f293788",
    "scrollbarSlider.hoverBackground": "#374151cc",
    "scrollbarSlider.activeBackground": "#374151ee",
    "editorIndentGuide.background": "#182030",
    "editorIndentGuide.activeBackground": "#1f2937",
    "editorBracketHighlight.foreground1": "#60a5fa",
    "editorBracketHighlight.foreground2": "#a78bfa",
    "editorBracketHighlight.foreground3": "#4ade80",
    "editorBracketHighlight.foreground4": "#facc15",
    "editorBracketHighlight.foreground5": "#f87171",
    "editorBracketHighlight.foreground6": "#22d3ee",
    "editorOverviewRuler.border": "#00000000",
    "editorOverviewRuler.errorForeground": "#ef444455",
    "editorOverviewRuler.warningForeground": "#facc1555",
  },
};

export const EDITOR_OPTIONS: editor.IStandaloneEditorConstructionOptions = {
  fontSize: 14,
  fontFamily: "'JetBrains Mono', 'Fira Code', 'Consolas', monospace",
  fontLigatures: true,
  minimap: {
    enabled: true,
    scale: 1,
    showSlider: "mouseover",
    renderCharacters: false,
  },
  scrollBeyondLastLine: false,
  wordWrap: "on",
  automaticLayout: true,
  tabSize: 4,
  insertSpaces: true,
  renderWhitespace: "selection",
  bracketPairColorization: { enabled: true, independentColorPoolPerBracketType: true },
  guides: {
    bracketPairs: true,
    indentation: true,
    highlightActiveIndentation: true,
  },
  suggest: {
    showKeywords: true,
    showSnippets: true,
    showClasses: true,
    showFunctions: true,
    showVariables: true,
    showInterfaces: true,
    showStructs: true,
    showEnums: true,
  },
  quickSuggestions: true,
  parameterHints: { enabled: true },
  autoClosingBrackets: "always",
  autoClosingQuotes: "always",
  autoIndent: "full",
  formatOnPaste: true,
  formatOnType: true,
  smoothScrolling: true,
  cursorBlinking: "smooth",
  cursorSmoothCaretAnimation: "on",
  padding: { top: 16, bottom: 16 },
  lineHeight: 24,
  letterSpacing: 0.3,
  renderLineHighlight: "all",
  renderLineHighlightOnlyWhenFocus: false,
  occurrencesHighlight: "singleFile",
  selectionHighlight: true,
  folding: true,
  foldingStrategy: "indentation",
  showFoldingControls: "mouseover",
  overviewRulerBorder: false,
  hideCursorInOverviewRuler: true,
  scrollbar: {
    verticalSliderSize: 6,
    horizontalSliderSize: 6,
    verticalScrollbarSize: 8,
    horizontalScrollbarSize: 8,
  },
  lineDecorationsWidth: 8,
  lineNumbersMinChars: 4,
};
